/* eslint-disable react/no-unescaped-entities */


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import Link from "next/link";
import Logo from "@/components/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app and typescript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center items-center flex-col min-h-screen bg-slate-100 font-instrument">
          <Link href="/">
         <Logo/>
          </Link>
          <div className="bg-white p-8 rounded-lg shadow-sm w-[500px] px-10 py-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
